- Vagrantfile
- bootstrap.sh
- vagrant/etc/apache2/sites-enabled/local.permanent.conf
- Move local development certs to S3 bucket
- Clean up apache2 config with lingering web-client path
To test, `vagrant up --provision`. A corresponding PR has been opened with the mdot repository to update the path to these certificates.
> Expunge last traces of the files repository

- README.md
Because of some recent changes to that repository, we can now bring up a full environment using the main branch.
```
cd website && git checkout dev
cd ../devenv
source .env
vagrant up --provision
```
> Eliminate note about website branch

- .env.template
- README.md
- Vagrantfile
This PR adds access to the `UPLOAD_SERVICE_SENTRY_DSN` environment variable, which is used to configure sentry in the upload-service process.
Resolves #13
> Add sentry DSN config

- README.md
- Vagrantfile
Use the newly created repo that consolidates the four PHP repos by mapping its subdirectories to their old names.
Developers will need to check out the new repo. The Vagrant machine can get the new mappings by shutting down the instance, and running `vagrant up` again.
PER-8117 Unify PHP repositories
> Use new unified back-end repo

- README.md
- Vagrantfile
- bin/deploy.sh
Building the web-app (formerly mdot) during `vagrant up` causes a lot of problems. The most immediately obvious one is the time it takes; building the web-app is a surprisingly compute- and I/O-heavy process, and both of those resources are diminished inside a virtual machine compared to the host operating system.
The bigger but more subtle problem is that running `vagrant up` breaks the `node_modules` directory on the host: the guest is (almost certainly) a different operating system, and `node_modules` is non-portable because it contains platform-specific code. Worse, we're running `npm install` with the argument `--no-bin-links`, which breaks npm scripts.
After discussion, we decided that we're willing to accept the cost of a slightly more difficult onboarding process for new …
> Stop building web-app during vagrant provisioning

- Vagrantfile
We restart each of our services on starting/resuming the Vagrant VM. The service names come from the infrastructure repo. Match the recently renamed upload-service unit from PR https://github.com/PermanentOrg/infrastructure/pull/55.
To test this, either redeploy with https://github.com/PermanentOrg/infrastructure/pull/55 checked out, or modify your local instance:
```sh
sudo service node-upload stop
sudo mv /etc/systemd/system/node-upload.service /etc/systemd/system/upload.service
sudo systemctl daemon-reload
sudo service upload start
```
> Use new name for upload service

- Vagrantfile
When we consolidated api, daemon, library, and task-runner into a single back-end repository, we continued to emulate the old layout by mounting the subdirectories of back-end into their original locations in `/data`. We did the same when packaging, so that we did not have to reconfigure Apache.
In order to allow us to use other subdirectories in back-end, and to support migrating from the disparate directories to the consolidated directory in local/dev/staging/prod, mount back-end directly.
Once the AMIs and Vagrant are in alignment, we can update Apache to use this new directory, but that work must be done later; this just sets the stage.
More immediately, this allows developers to run PHPLint from within Vagrant (instead of only on the host), and will enable us to add more such tools. …
> Mount back-end repo in Vagrant

- Vagrantfile
- bin/deploy.sh
I've been running our Vagrant VM with some modifications for a while, and I'd like to get them merged so that I can stop managing them locally.
First, further reduce the memory allocated to the VM, down to 1GB; this makes the VM a bit lighter weight and easier to run alongside more demanding applications on the host.
Second, install [Byobu](https://www.byobu.org/); it does not default to being enabled, so this should not affect anyone else - it just makes it easier for me to opt into using it, by letting me skip the install step.
Finally, fix an [issue](https://bugs.mysql.com/bug.php?id=68449) with the `mysql` text UI by creating a configuration file for root, so that I can hit `ctrl-w` in `sudo mysql` and not lose all my work.
> Customizations

- bin/deploy.sh
This PR installs the tooling for PHP linting as part of provisioning.
In order to actually run the linters you would:
```
cd /data/www/back-end
./tools/phplint/vendor/bin/phplint
./tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run -v
```
This is also documented in the `back-end/README.md`
Resolves #38
> Install PHP linting tooling

- bin/deploy.sh
This PR prevents a situation where running local tests would modify the test files.
Our unit tests already copy needed files from `/data/www/api/tests/files` into `/data/tmp/unittest`.
Once this is merged we will all need to run the following in local:
```
rm /data/tmp/unittest
mkdir /data/tmp/unittest
```
You can also test this change locally by running the above command in your environment and then running the unit tests; you should see successful tests AND not see any git changes when you run `git status` in your back-end repository.
> Don't symlink test files

- bin/deploy.sh
Rather than run `apt-get install` multiple times, collect all the packages into a single invocation, split them one-per-line so that it's easy to change the list, and sort them alphabetically so that it's obvious where to add new packages.
> Consolidate apt package installation

- bin/deploy.sh
Install the PostgreSQL server, create users, and grant permissions.
I (Cecilia) changed this to set the vagrant user as a superuser (which I'd like @liam-lloyd's take on) and to use a password as we do in other environments.  This will have corresponding PRs in the back-end and infrastructure repos which I will link shortly.
PER-8935 Add capability to run devenv against a PostgreSQL database
> Install and configure PostgreSQL

- bin/deploy.sh
Looking at the back-end repo there is not such file specified by the path `/data/www/library/postgres-base.sql` rather we have `/data/www/library/postgresql/base.sql` and so this commits correct the deploy script to point to that instead.
Signed-off-by: Fon E. Noel NFEBE <fenn25.fn@gmail.com>
> Point to correct postgres schema

- .env.template
- Vagrantfile
- bin/deploy.sh
You should be able to check this by running `vagrant halt` and then `vagrant up --provision` -- no need to destroy your VM entirely (though note you'll see a lot of errors when you try to reprovision an existing box, mostly around "this database table already exists").
To test this, add a migration in `back-end/library` and reprovision. You can create one as documented by dbmate or use the [example](https://github.com/PermanentOrg/back-end/commit/9162cd56a5e82ba5f78e0227ed75244933cc99b0) I pushed to the back-end repo. Let me know if you'd rather I opened a PR with a comment-only example.
I alphabetized the environment variables in the Vagrantfile. It would be better to save the connection string in .env, probably - is that worth doing?
This requires …
> Run migrations with dbmate

- .env.template
- .gitignore
- README.md
- docker-compose.yml
- nginx.conf
Before we start writing production code in stela, we need it to be part of our local development environment. This commit adds a docker-compose file which brings up stela, a postgres database to be shared by stela and back-end, and an nginx server to properly route requests to either back-end or stela.
Related PRs:
- https://github.com/PermanentOrg/back-end/pull/350
- https://github.com/PermanentOrg/stela/pull/3
> Incorporate stela into the local environment

- README.md
This is just a basic README change.
When destroying and rebuilding my devenv, I was confused when I got to downloading the SSL certs since I didn't have `aws` installed. This links to AWS CLI installation instructions for various operating systems.
> Add line to AWS CLI install instructions.

- bin/deploy.sh
- docker-compose.yml
Currently we run the memcached instance our local back-end relies on on a Vagrant VM. We want to move away from Vagrant, so this commit moves that memcached instance to a docker container.
> Move local memcached instance to Docker

- Vagrantfile
- bin/deploy.sh
Currently, our Vagrant VM runs a MySQL database and a PostgreSQL database. We don't need the MySQL one anymore because we're not using MySQL at all anymore, and we don't need the PostgreSQL one anymore because local instances of our application now use a dockerized PostgreSQL database. In light of this, this commit removes both databases from the Vagrant VM.
> Remove databases from Vagrant VM

- README.md
While I was working on local I was getting CORS error when I logout. I later realized that it was because the app was redirecting to IP address on logout. We already have notes about this on readme, but adding this to specify about CORS error.
> Adding Instructions about CORS error

- bin/deploy.sh
- docker-compose.yml
Currently, migrations run on the local database on `vagrant up`, but it is sometimes convenient to run these migrations without bringing vagrant down and back up again, so this commit adds migrations to the setup process that runs for the local database on `docker compose up`.
> Run migrations on local DB when bringing up docker containers

- README.md
- bin/repo-sync.sh
This PR adds the `stela` repository to the sync script.
Related to #56
> Add stela to auto-sync

- README.md
- docker-compose.yml
- nginx.conf
Presently, the nginx instance that routes requests to either back-end or stela in the local environment only supports https. Because it would take some effort to set up stela to be able to make https calls in the local environment, and because this effort wouldn't have any meaningful benefit, it is preferable to allow http calls. This commit updates the docker compose and nginx.conf to do this.
> Allow HTTP connections in the local environment

- docker-compose.yml
We're seeing strange behavior in back-end CI where database_setup appears to use an outdated version of base.sql rather than picking up the one in the stela directory. We think maybe a writeable volume will fix this.
> Use a writable volume for base.sql in database_setup

- docker-compose.yml
Reverts PermanentOrg/devenv#65 Reverting because it didn't solve our problem, and it makes more sense for this to be a read only volume
> Revert "Use a writable volume for base.sql in database_setup"

- docker-compose.yml
Removing ts-node from stela involved changing how it does hot-loading in the local environment. One effect of this is that it no longer uses the /dev directory; this commit updates docker-compose.yml to reflect that.
> Update docker-compose to reflect stela updates

- Vagrantfile
Debian 10 will exit long term support this year, so we are upgrading our infrastructure to Debian 11. The local environment should match the deployed environments as much as practicable, so this commit updates the vagrant box to Debian 11 as well.
> Upgrade vagrant box to Debian 11

- .env.template
- docker-compose.yml
This PR changes our docker-compose so that the psql port bound to host is configurable.  This means developers who run psql on their machine can pick an open port instead.
As part of this change we also update the docker-compose so that back-end is talking directly to the database rather than routing through the host
Resolves #57
> Make the bound psql port configurable
